### ISSUE TITLE
Add exists, has_type, has_mode, has_owner and has_group assertions to assert_that_file role

### ISSUE THREAD

**Issue by marcwrobel** [marcwrobel/ansible-collection-assertions#12]
Currently making assertions on files and files content require both the role `assert_that_file` and `assert_that_path` :

```yaml
- name: 'Assert that /tmp/test exists, is a file, have mode 0640 and belongs to root:root'
  include_role:
    name: 'marcwrobel.assertions.assert_that_path'
  vars:
    path: '/tmp/test'
    has_type: 'file'
    has_mode: '0640'
    has_owner: 'root'
    has_group: 'root'

- name: 'Assert that /tmp/test is Ansible managed'
  include_role:
    name: 'marcwrobel.assertions.assert_that_file'
  vars:
    path: '/path/to/file'
    has_content_matching: '^# Ansible managed'
```

But making assertions on files is one of the most common type of assertion. In order to reduce the code needed for that it should be possible to make `exists`, `has_type`, `has_mode`, `has_owner` and `has_group` assertions with `assert_that_file` role.
